package main

import (
	"log"

	"github.com/Necroforger/Fantasia/modules/information"
	"github.com/Necroforger/Fantasia/system"
)

////////////////////////////////////////////
//            Generated by
//          tools/genmodules
////////////////////////////////////////////

// ModuleConfig ...
type ModuleConfig struct {
	Inverted    bool
	Information bool
}

// NewModuleConfig returns a new module configuration
func NewModuleConfig() *ModuleConfig {
	return &ModuleConfig{
		Inverted:    false,
		Information: true,
	}
}

// RegisterModules builds a list of modules into the given system
func RegisterModules(s *system.System, config ModuleConfig) {
	if (config.Inverted && !config.Information) || config.Information {
		s.CommandRouter.SetCategory("Information")
		s.BuildModule(&information.Module{})
		log.Println("loaded information module...")
	}
}
